Contact/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cards.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cards/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'cards'

urlpatterns = [
    path('', views.home, name='home'),
    path('my-contacts/', views.contactList, name='contactList'),
    path('my-contacts/<id>', views.contactDetail, name='contactDetail'),
    path('create/', views.createCard, name="createCard"),
    path('edit/<id>', views.editCard, name="editCard"),
    path('delete/<id>', views.deleteCard, name="deleteCard")
]

cards/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib.auth.models import User

from django.core.validators import MaxLengthValidator
# Create your models here.


class Card(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    firstName = models.CharField(max_length = 200)
    middleName = models.CharField(max_length = 200, null=True, blank=True)
    lastName = models.CharField(max_length = 200)
    nickName = models.CharField(max_length = 200, null=True, blank=True)
    gender = models.CharField(max_length=50, choices=(
        ('Male', 'Male'),
        ('Female', 'Female')
    ))
    info = models.CharField(max_length=30, null=True, blank=True)
    emailAddress = models.EmailField(max_length = 200, null=True, blank=True)
    Address	= models.CharField(max_length = 256, null=True, blank=True)
    City = models.CharField(max_length = 200, null=True, blank=True)
    postalCode = models.IntegerField(null=True, blank=True)
    State = models.CharField(max_length = 200, null=True, blank=True)
    Country = models.CharField(max_length = 200, null=True, blank=True, default = "India")
    image = models.ImageField(upload_to='images/', null=True, blank = True)
    date_added = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.firstName

    #For making the newly added data to appear first
    class Meta:
        ordering = ['-id']

# class additionalWorkInfo(models.Model):
#     user = models.ForeignKey(User, on_delete = models.CASCADE)
#     card = models.ForeignKey(Card, on_delete = models.CASCADE)
#     workType = models.CharField(max_length=50, null=True, blank=True, choices=(
#         ('job', 'Job'),
#         ('business', 'Business')
#     ))
#     workEmailAddress = models.EmailField(max_length = 200, null=True, blank=True)
#     workAddress	= models.CharField(max_length = 256, null=True, blank=True)
#     workCity = models.CharField(max_length = 200, null=True, blank=True)
#     workPostalCode = models.IntegerField(null=True, blank=True)
#     workState = models.CharField(max_length = 200, null=True, blank=True)
#     workCountry	= models.CharField(max_length = 200, null=True, blank=True, default = "India")
#     workWebsite = models.CharField(max_length = 200, null=True, blank=True)
#     workMobile = models.IntegerField(null=True, blank=True)
#     workPhone = models.IntegerField(null=True, blank=True)
#     workFax = models.IntegerField(null=True, blank=True)
#     workCompany	= models.CharField(max_length = 200, null=True, blank=True)
#     workJobTitle = models.CharField(max_length = 200, null=True, blank=True)


#     def __str__(self):
#         return str(self.card)

    #For making the newly added data to appear first
    class Meta:
        ordering = ['-id']

class Contact(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    card = models.ForeignKey(Card, on_delete = models.CASCADE)
    type = models.CharField(max_length=100, choices = (
                    ('Landline', 'LandLine'),
                    ('Mobile', 'Mobile'),
                    ('Fax', 'Fax')
                )
            )
    number = models.CharField(max_length=10)

    def __str__(self):
        return (str(self.card)+ " | "+str(self.type))

cards/forms.py
from django import forms

from .models import Card, Contact

class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        exclude = ('user', 'date_added')
    
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ('user', 'card')

cards/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import formset_factory, modelformset_factory

from .models import Contact, Card
from .forms import CardForm, ContactForm
# Create your views here.
def home(request):

    context = {

    }

    return render(request, 'cards/home.html', context)

def contactList(request):

    context = {
        'cards' : Card.objects.filter(user=request.user)
    }

    return render(request, 'cards/contactList.html', context)

def contactDetail(request, id):

    card = get_object_or_404(Card, id=id)
    context = {
        'card' : card,
        'contacts' : Contact.objects.filter(user=request.user, card=card),
        # 'workInfo' : get_object_or_404(additionalWorkInfo, user=request.user, card=card)
    }

    return render(request, 'cards/contactDetail.html', context)


def createCard(request):
    contactFormset = formset_factory(ContactForm, max_num=0)
    formset = contactFormset()
    form = CardForm()
    if request.method == "POST":
        print(request.POST)
        form = CardForm(request.POST,request.FILES)
        formset = contactFormset(request.POST)
        if all([form.is_valid(), formset.is_valid()]):
            card = form.save(commit=False)
            card.user = request.user
            card.save()
            
            for contactForm in formset:
                temp = contactForm.save(commit=False)
                temp.user = request.user
                temp.card = card
                temp.save()
            
            
            return redirect('cards:contactList')
        else:
            print("Form invalid", formset.errors)
    context = {
        'cardForm' : form,
        'formset' : formset
    }

    return render(request, 'cards/createCard.html', context)

def editCard(request, id):

    card = get_object_or_404(Card, id=id)
    form = CardForm(instance = card)
    q = Contact.objects.filter(user=request.user, card=card)
    contactFormset = modelformset_factory(Contact, form=ContactForm, extra=0, can_delete=True)
    formset = contactFormset(queryset=q)

    if request.method == 'POST':
        form = CardForm(request.POST, request.FILES, instance = card)
        formset = contactFormset(request.POST, queryset=q)

        if all([form.is_valid(), formset.is_valid()]):
            form = form.save(commit=False)
            form.save()
            for cForm in formset:
                print(cForm.cleaned_data)
                temp = cForm.save(commit=False)
                temp.user = request.user
                temp.card = card
                temp.save()
            for dform in formset.deleted_forms:
                id = dform.cleaned_data['id']
                contact = Contact.objects.get(id=id.id)
                contact.delete()
            return redirect('cards:contactDetail', card.id)

    context = {
        'card' : card,
        'form' : form,
        'formset' : formset
    }

    return render(request, 'cards/editCard.html', context)

def deleteCard(request, id):
    card = get_object_or_404(Card, id=id)
    card.delete()
    return redirect('cards:contactList')


    

templates/base.html
<!doctype html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Contacts App</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">         
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'cards:contactList' %}">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'cards:contactList' %}">My Contacts</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'cards:createCard' %}">+Add Contact</a>
                  </li>
                  
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
        </nav>

        <div class="container">
          {% block bodyblock %}

          {% endblock bodyblock %}
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    </body>
</html>

templates/cards/contactDetail.html
{% extends 'base.html' %}
{% block bodyblock %}
    <h1>Hello From Contact Details!!</h1> 
    <a href="{% url 'cards:editCard' card.id %}" >Edit</a>
    <a href="{% url 'cards:deleteCard' card.id %}" >Delete Card</a>
    {{card.firstName}}

    <h3>Contacts</h3>
    {% for contact in contacts %}
        <p>{{contact.type}} - {{ contact.number}}</p>
    {% endfor %}
    
    {% if workInfo %}
    <h3>Work Info</h3>
    {{workInfo.workCountry}}
    {% endif %}
{% endblock bodyblock %}

templates/cards/contactList.html
{% extends 'base.html' %}
{% block bodyblock %}
    <h1>My Contacts</h1> 
    <div class="row">
    
        {% for card in cards %}
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="
                    card mb-3 
                    {% if card.gender == 'Male' %} 
                        border-success 
                    {% else %}
                        border-info    
                    {% endif %}" style="max-width: 540px;">
                    <a href="{% url 'cards:contactDetail' card.id %}"> 
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{ card.image.url }}" class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title text-dark">{{card.firstName}} {{card.lastName}}</h5>
                                    <p class="card-text">{{ card.gender }}</p>
                                    <p class="card-text">Email - {{ card.emailAddress }}</p>
                                    <p class="card-text"><small class="text-muted">Added - {{ card.date_added }}</small></p>
                                </div>
                            </div>
                        </div>
                    </a>

                    
                </div>
            </div>
            
        {% endfor %}
    </div>
{% endblock bodyblock %}

templates/cards/createCard.html
{% extends 'base.html' %}
{% block bodyblock %}
        <h1>Hello From Create Card!!</h1> 
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{cardForm.as_p}}
            {% if formset %}
            {{ formset.management_form}}
            <div id="contact-formset-list" >
                {% for form in formset %}
                    <div class="contact-formset">
                        {{ form }}
                    </div> 
                {% endfor %}
            </div>
            <div id="empty-form" class="hidden" >{{ formset.empty_form }}</div>
            <button id="add-contact" type="button">Add Contact</button>
            {% endif %}
            
            <input type="submit" name="Submit">
        </form>

        <script type="text/javascript">
            const btn = document.getElementById("add-contact")
            const totalNewForms = document.getElementById("id_form-TOTAL_FORMS")
            
            btn.addEventListener('click', (e) => {
                if (e) {
                    e.preventDefault()
                }
                const currentForms = document.getElementsByClassName("contact-formset")
                const currentFormCount = currentForms.length
                const contactFormTarget = document.getElementById('contact-formset-list')
                const emptyform = document.getElementById('empty-form').cloneNode(true)
                // const clone = emptyform.cloneNode(true)
                emptyform.setAttribute('class', 'contact-formset')
                emptyform.setAttribute('id', `form-${currentFormCount}`)
                const regex = RegExp('__prefix__', 'g')
                emptyform.innerHTML = emptyform.innerHTML.replace(regex, currentFormCount)
                totalNewForms.setAttribute('value', currentFormCount + 1)
                contactFormTarget.append(emptyform)
            })

        </script>

{% endblock bodyblock %}

templates/cards/editCard.html
{% extends 'base.html' %}
{% block bodyblock %}
        <h1>Hello From Edit Card!!</h1> 
        {{card.firstName}}
        <form method="POST", enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {{ formset.management_form}}
            <div id="contact-formset-list" >
                {% for form in formset %}
                    <div class="contact-formset">
                        {{ form }}
                    </div> 
                {% endfor %}
            </div>
            <div id="empty-form" class="hidden" >{{ formset.empty_form }}</div>
            <button id="add-contact" type="button">Add Contact</button>
            
            <input type="submit" value="Update">
        </form>
        

        <script type="text/javascript">
            const btn = document.getElementById("add-contact")
            
            
            btn.addEventListener('click', (e) => {
                if (e) {
                    e.preventDefault()
                }
                const totalNewForms = document.getElementById("id_form-TOTAL_FORMS")
                const currentForms = document.getElementsByClassName("contact-formset")
                const currentFormCount = currentForms.length
                const nextFormValue = currentFormCount
                const contactFormTarget = document.getElementById('contact-formset-list')
                const emptyform = document.getElementById('empty-form').cloneNode(true)
                // const clone = emptyform.cloneNode(true)
                emptyform.setAttribute('class', 'contact-formset')
                emptyform.setAttribute('id', `form-${nextFormValue}`)
                const regex = RegExp('__prefix__', 'g')
                emptyform.innerHTML = emptyform.innerHTML.replace(regex, nextFormValue)
                totalNewForms.setAttribute('value', nextFormValue + 1)
                
                contactFormTarget.append(emptyform)
            })
        </script>
        
{% endblock bodyblock %}

templates/cards/home.html
{% extends 'base.html' %}
{% block bodyblock %}
  <h1>Hello from Cards!!</h1>
{% endblock bodyblock %}